# Generated by Django 4.0.4 on 2022-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_rename_refund_worker_dispatched_order_refundworkerdispatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Genocide', 'Genocide'), ('Assasination', 'Assasination'), ('Silent', 'Silent'), ('Standard', 'Standard Equipment'), ('Banana', 'Banana Goodies')], default='Standard', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('S', 'secondary'), ('P', 'primary'), ('ss', 'success'), ('w', 'warning')], default='D', max_length=500),
        ),
    ]
